/**
 * Local Visibility Score PDF — emailed to wedge leads and viewable in-app.
 *
 * Uses @react-pdf/renderer (server-side). Keep the layout tight: this PDF
 * needs to load on a phone in 2 seconds and be skim-able in 30.
 */
import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import React from "react";

import type { DeterministicOutput, NarrativeOutput } from "@/lib/skills/local_visibility_audit";

const s = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: "Helvetica", color: "#111" },
  brand: { fontSize: 9, color: "#666", marginBottom: 6 },
  h1: { fontSize: 22, fontWeight: 700, marginBottom: 4 },
  sub: { fontSize: 11, color: "#444", marginBottom: 18 },
  scoreRow: { flexDirection: "row", alignItems: "center", marginBottom: 18 },
  grade: { fontSize: 56, fontWeight: 700, marginRight: 12, lineHeight: 1 },
  scoreText: { fontSize: 12, color: "#444" },
  sectionTitle: { fontSize: 14, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  fix: { marginBottom: 10, padding: 8, backgroundColor: "#f7f7f8", borderRadius: 4 },
  fixTitle: { fontSize: 12, fontWeight: 700, marginBottom: 2 },
  fixWhy: { color: "#444" },
  fixDo: { marginTop: 4, fontWeight: 700 },
  insightRow: { flexDirection: "row", marginBottom: 4 },
  sevDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6, marginTop: 4 },
  insightText: { flex: 1 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#888" },
});

const SEVERITY_COLOR: Record<string, string> = {
  critical: "#c62828",
  warning: "#ef6c00",
  info: "#1565c0",
  win: "#2e7d32",
};

export async function renderLvsReportPdf(args: {
  businessName: string;
  zip: string;
  deterministic: DeterministicOutput;
  narrative?: NarrativeOutput;
  generatedAt: Date;
}): Promise<Buffer> {
  const { businessName, zip, deterministic, narrative, generatedAt } = args;

  const doc = (
    <Document title={`Local Visibility Score — ${businessName}`}>
      <Page size="LETTER" style={s.page}>
        <Text style={s.brand}>NEMO LOCAL · LOCAL VISIBILITY SCORE</Text>
        <Text style={s.h1}>{businessName}</Text>
        <Text style={s.sub}>ZIP {zip} · generated {generatedAt.toISOString().slice(0, 10)}</Text>

        <View style={s.scoreRow}>
          <Text style={s.grade}>{deterministic.grade}</Text>
          <View>
            <Text style={s.scoreText}>Score: {deterministic.score} / 100</Text>
            <Text style={s.scoreText}>
              {deterministic.insights.filter((i) => i.severity === "critical").length} critical ·{" "}
              {deterministic.insights.filter((i) => i.severity === "warning").length} warning
            </Text>
          </View>
        </View>

        {narrative ? (
          <>
            <Text style={s.sectionTitle}>{narrative.headline}</Text>
            <Text style={{ marginBottom: 10 }}>{narrative.summary}</Text>

            <Text style={s.sectionTitle}>Top fixes</Text>
            {narrative.topFixes.map((f, i) => (
              <View key={i} style={s.fix} wrap={false}>
                <Text style={s.fixTitle}>{i + 1}. {f.title}</Text>
                <Text style={s.fixWhy}>{f.why}</Text>
                <Text style={s.fixDo}>Do this: {f.do_this}</Text>
              </View>
            ))}
          </>
        ) : null}

        <Text style={s.sectionTitle}>All findings</Text>
        {deterministic.insights.map((ins, i) => (
          <View key={i} style={s.insightRow}>
            <View style={[s.sevDot, { backgroundColor: SEVERITY_COLOR[ins.severity] ?? "#888" }]} />
            <View style={s.insightText}>
              <Text style={{ fontWeight: 700 }}>{ins.title}</Text>
              <Text>{ins.message}</Text>
              <Text style={{ color: "#444" }}>→ {ins.action}</Text>
            </View>
          </View>
        ))}

        <Text style={s.footer}>
          Nemo Local · nemo.local · Generated by the local_visibility_audit skill ·
          Findings tagged with stable rule ids; reach out for the methodology doc.
        </Text>
      </Page>
    </Document>
  );

  return await renderToBuffer(doc);
}
